### ISSUE TITLE
Blessed Sacrament Chapel in MHT Church

### ISSUE THREAD

**Issue by simonle0525** [hungple/mht-building#5]
### Information
Name of Inspector:	Hung Le, Paul Tran, Tita Marte			
Building:	MHT Church			
Room or Area:  Blessed Sacrament Chapel			
Inspect Date: January 14, 2018

### Assessment/Observation/Comment**:
Water leak on the ceiling towards back of chapel

### Plan of Correction
Fix the leak

**Comment by PaulTran54** [comment]
Same as issue #3
